/*

DO NOT EDIT THIS FILE.

This contains the core JS for handling navigation and loading of submitted styles.

Your added JS, if any, should initialize itself through a function called initializePage().

*/

// nav function to hide/show menu items 
function clickNav(bodyClicked) {
    let navHandle = document.querySelector("nav");
    let burgerWasClicked = navHandle.classList.contains("navClicked");
    if (!bodyClicked) navHandle.classList.toggle("navClicked"); // ...toggle a "clicked" class on the nav
    else navHandle.classList.remove("navClicked");

    // remove menu .navClicked if burger is closed
    if (burgerWasClicked || bodyClicked) {
        let allMenus = document.querySelectorAll("nav > ul > li");
        for (const eachMenu of allMenus) {
            eachMenu.classList.remove("navClicked");
        }
    }
}

// read style from URL string, if available
function parseQuery() {
    // get the query string and convert to object to get style
    const queryString = window.location.search; 
    const queryParams = new URLSearchParams(queryString);

    // make sure style was passed
    if (queryParams.get("style") == null) {
        styleDirectory = "default";
        console.log("No style submitted, reverting to default.");
    } else {
        styleDirectory = queryParams.get("style");
    }

    // we've got a style directory, let's load it
    loadStyle(styleDirectory);
}

// load requested style, if possible
function loadStyle(getStyleDirectory) {

    console.log(`Loading: ${getStyleDirectory}`);

    // adapt path to local context
    const urlRoot = location.pathname;
    console.log("url root:" + urlRoot);

    // add chosen CSS file
    let addedStyle = document.createElement("link");
    addedStyle.setAttribute("rel", "stylesheet");
    addedStyle.setAttribute("media", "all");
    addedStyle.setAttribute("href", `${urlRoot}${getStyleDirectory}/styles.css`);
    document.head.append(addedStyle);

    // add chosen JS file
    loadJS(`${urlRoot}${getStyleDirectory}/scripts.js`);

    // change page title
    document.title += ` (${getStyleDirectory})`;
}

// load a new JS file from a given path and run the function "initialize" from it
async function loadJS(fromPath) {
    let newJS = await import(fromPath);
    newJS.initializePage();
}

// generic ajax function for getting data
async function getData(url, options = {}) {
    try {
        const response = await fetch(url, options);
        if (response.ok) {
            const result = await response.json();
            return result;
        } else {
            throw(response.status);
        }
    } catch (error) {
        console.error(error);
    }
}

// dynamically style info from JSON data in core-style-menu.js
async function loadStyleMenu() {
    document.querySelector("#styleList").innerHTML = "";
    getData("core-style-menu.js").then(function(menuItems) {
        for (oneItem of menuItems) {
            document.querySelector("#styleList").innerHTML += `<li><a href="?style=${oneItem.path}">${oneItem.label}</a></li>`;
        }
    });
}

// load click events after DOM loaded
document.addEventListener("DOMContentLoaded", function () {

    // dynamically generate style menu from json file
    loadStyleMenu();

    // respond to clicks on the burger
    document.querySelector("#navBurger").addEventListener("click", function (event) {
        clickNav(false);
    });

    // handles to all topline nav items
    let allMenus = document.querySelectorAll("nav > ul > li");
    for (const eachMenu of allMenus) {
        // loop through collection of handles individually
        eachMenu.addEventListener("click", function (event) {
            let wasClicked = eachMenu.classList.contains("navClicked");
            let allMenus2 = document.querySelectorAll("nav > ul > li");
            for (const eachMenu2 of allMenus2) {
                eachMenu2.classList.remove("navClicked");
            }
            if (!wasClicked) {
                eachMenu.classList.add("navClicked"); // if this is newly clicked, add click class back
            }
        });
    }

    // close nav if someone clicks outside nav
    document.querySelector("html").addEventListener("click", function (event) {
        if (!event.target.closest("nav")) {
            clickNav(true);
        }
    });

    // load requested style, if any
    parseQuery();

});